markdown: redcarpet
name: A content guide for the Federalist platform
exclude:
- go
- copy-template
- Gemfile
- Gemfile.lock
- README.md
- LICENSE.md

permalink: pretty
highlighter: rouge

sass:
  style: :compressed

# Author/Organization info to be displayed in the templates
author:
  name: 18F
  url: https://18f.gsa.gov

# Point the logo URL at a file in your repo or hosted elsewhere by your organization
logourl: /assets/img/18f-logo.png
logoalt: 18F logo

# Navigation
# List links that should appear in the site sidebar here
navigation:
- text: Introduction
  url: index.html
  internal: true
- text: Writing content for your homepage
  url: writing-content-for-your-federalist-homepage/
  internal: true
- text: Best practices for content
  url: best-practices-for-content/
  internal: true
- text: Writing about your team
  url: writing-who-we-are/
  internal: true
- text: Writing about your research
  url: writing-what-we-do/
  internal: true
- text: Writing clear contact forms
  url: contact-forms/
  internal: true

repos:
- name: Federalist Content Guide
  description: Main repository
  url: https://github.com/18F/federalist-content-guide

google_analytics_ua: UA-48605964-19

back_link:
  url: "https://pages.18f.gov/guides/"
  text: Read more 18F Guides

defaults:
  -
    scope:
      path: ""
    values:
      layout: "guides_style_18f_default"
